on: 
  workflow_dispatch:
jobs:
  main_job:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Action step
      uses: ./
      with:
        file: ./sample/sample.e
        output: ./sample/sample.o
    - name: upload result
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: ${{ github.workspace }}/sample/sample.o
